apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mentr-webui
  namespace: mentr
spec:
  rules:
    - host: ki.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mentr-webui
                port:
                  number: 8080
